# Generated by Django 5.2.3 on 2025-07-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewratingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewratingmodel',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewratingmodel',
            name='review',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='reviewratingmodel',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
