# Generated by Django 5.2.3 on 2025-07-29 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_reviewrating_delete_reviewratingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/products')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.productmodel')),
            ],
            options={
                'verbose_name': 'productgallery',
                'verbose_name_plural': 'Product Gallery',
            },
        ),
    ]
