# Generated by Django 5.2.3 on 2025-07-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_ordermodel_tax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='total',
            new_name='order_total',
        ),
    ]
