# Generated by Django 5.2.3 on 2025-07-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderproduct_variation_orderproduct_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_total',
            field=models.FloatField(),
        ),
    ]
