# Generated by Django 5.2.3 on 2025-07-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordermodel_tax_alter_ordermodel_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_price',
            field=models.FloatField(default=0.0),
        ),
    ]
